version: '2'
services:
    boris-app:
        image: boris
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_CASSANDRA_CONTACTPOINTS=boris-cassandra
            - JHIPSTER_SLEEP=30 # gives time for the Cassandra cluster to start and execute the migration scripts
            - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=kafka
            - SPRING_CLOUD_STREAM_KAFKA_BINDER_ZK_NODES=zookeeper
        ports:
            - 8080:8080
    boris-cassandra:
        extends:
            file: cassandra-cluster.yml
            service: boris-cassandra
    boris-cassandra-node:
        image: cassandra:3.9
        environment:
            - CASSANDRA_SEEDS=boris-cassandra
    boris-cassandra-migration:
        extends:
            file: cassandra-migration.yml
            service: boris-cassandra-migration
        environment:
            - CREATE_KEYSPACE_SCRIPT=create-keyspace-prod.cql
    kafka:
        extends:
            file: kafka.yml
            service: kafka
        environment:
            - KAFKA_ADVERTISED_HOST_NAME=kafka
    zookeeper:
        extends:
            file: kafka.yml
            service: zookeeper
